language: cpp
compiler: clang
jobs:
  include:
  - stage: test
    dist: bionic
    services:
      -xvfb
    os: linux
    script:
      - make -j3
      - make tests
      - build/tests
    deploy:
      provider: script
      skip_cleanup: true
      script: bash deploy.bash linux    
      on:
        all_branches: true
  - stage: test
    os: osx
    osx_image: xcode11.3
    before_install:
      - wget -q "https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.0.1.dmg"
      - hdiutil attach SDL2_net-2.0.1.dmg
      - sudo cp -R /Volumes/SDL2_net/SDL2_net.framework /Library/Frameworks/
      - wget -q "https://www.libsdl.org/release/SDL2-2.0.9.dmg"
      - hdiutil attach SDL2-2.0.9.dmg
      - sudo cp -R /Volumes/SDL2/SDL2.framework /Library/Frameworks/
    script: 
      - make -j3 macapp SIGNING_ID=NONE
      - make tests
      - build/tests
    deploy:
      provider: script
      skip_cleanup: true
      script: bash deploy.bash mac
      on:
        all_branches: true
  - stage: test
    os: windows
    before_install:
      - choco install msys2
    script: 
      - powershell -executionpolicy bypass -file travis-windows.ps1
      - ps -ef
    deploy:
      provider: script
      skip_cleanup: true
      script: bash deploy.bash windows
      on:
        all_branches: true
    after_script:
      - taskkill -IM "gpg-agent.exe" -F
addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev
    - libegl1-mesa-dev
    - libgles2-mesa-dev
    - libsdl2-net-dev
    - libdirectfb-dev

